// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/administrativo/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/administrativo/clientes">> = Specific
  const handler = {} as typeof import("../../src/app/administrativo/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/administrativo/contratos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/administrativo/contratos">> = Specific
  const handler = {} as typeof import("../../src/app/administrativo/contratos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compras/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compras/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/compras/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compras/fornecedores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compras/fornecedores">> = Specific
  const handler = {} as typeof import("../../src/app/compras/fornecedores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compras/importacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compras/importacao">> = Specific
  const handler = {} as typeof import("../../src/app/compras/importacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compras/painel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compras/painel">> = Specific
  const handler = {} as typeof import("../../src/app/compras/painel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compras/produtos-pendentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compras/produtos-pendentes">> = Specific
  const handler = {} as typeof import("../../src/app/compras/produtos-pendentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard-tv/configuracoes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-tv/configuracoes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard-tv/configuracoes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard-tv/exibir/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-tv/exibir/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard-tv/exibir/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard-tv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-tv">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard-tv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/definir-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/definir-senha">> = Specific
  const handler = {} as typeof import("../../src/app/definir-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dp-rh/cadastros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dp-rh/cadastros">> = Specific
  const handler = {} as typeof import("../../src/app/dp-rh/cadastros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dp-rh/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dp-rh/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dp-rh/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dp-rh/funcionarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dp-rh/funcionarios">> = Specific
  const handler = {} as typeof import("../../src/app/dp-rh/funcionarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dp-rh/movimentacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dp-rh/movimentacoes">> = Specific
  const handler = {} as typeof import("../../src/app/dp-rh/movimentacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dp-rh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dp-rh">> = Specific
  const handler = {} as typeof import("../../src/app/dp-rh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/esqueci-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esqueci-senha">> = Specific
  const handler = {} as typeof import("../../src/app/esqueci-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/estoque-logistica/importacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque-logistica/importacao">> = Specific
  const handler = {} as typeof import("../../src/app/estoque-logistica/importacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/estoque-logistica/novas-propostas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque-logistica/novas-propostas">> = Specific
  const handler = {} as typeof import("../../src/app/estoque-logistica/novas-propostas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/estoque-logistica/roteiro-entrega/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estoque-logistica/roteiro-entrega">> = Specific
  const handler = {} as typeof import("../../src/app/estoque-logistica/roteiro-entrega/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/auditoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/auditoria">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/auditoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/cadastros/motoristas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/cadastros/motoristas">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/cadastros/motoristas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/cadastros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/cadastros">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/cadastros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/cadastros/pessoas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/cadastros/pessoas">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/cadastros/pessoas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/cadastros/tecnicos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/cadastros/tecnicos">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/cadastros/tecnicos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/cadastros/veiculos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/cadastros/veiculos">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/cadastros/veiculos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/configuracao-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/configuracao-email">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/configuracao-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/notificacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/notificacoes">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/notificacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/perfis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/perfis">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/perfis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/responsabilidades-notificacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/responsabilidades-notificacoes">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/responsabilidades-notificacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/sla-os/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/sla-os">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/sla-os/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/tipos-proposta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/tipos-proposta">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/tipos-proposta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ferramentas/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ferramentas/usuarios">> = Specific
  const handler = {} as typeof import("../../src/app/ferramentas/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/dre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro/dre">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/dre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/filiais/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro/filiais">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/filiais/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/fluxo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro/fluxo">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/fluxo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/importacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro/importacoes">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/importacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/notas-recebidas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro/notas-recebidas">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/notas-recebidas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/pagar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro/pagar">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/pagar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/plano-contas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro/plano-contas">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/plano-contas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/receber/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeiro/receber">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/receber/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/geolocalizacao/mapa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/geolocalizacao/mapa">> = Specific
  const handler = {} as typeof import("../../src/app/geolocalizacao/mapa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/geolocalizacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/geolocalizacao">> = Specific
  const handler = {} as typeof import("../../src/app/geolocalizacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/geolocalizacao/relatorio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/geolocalizacao/relatorio">> = Specific
  const handler = {} as typeof import("../../src/app/geolocalizacao/relatorio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/grandes-projetos/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grandes-projetos/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/grandes-projetos/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/grandes-projetos/projetos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grandes-projetos/projetos/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/grandes-projetos/projetos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/grandes-projetos/projetos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grandes-projetos/projetos">> = Specific
  const handler = {} as typeof import("../../src/app/grandes-projetos/projetos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/grandes-projetos/relatorios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grandes-projetos/relatorios">> = Specific
  const handler = {} as typeof import("../../src/app/grandes-projetos/relatorios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/minha-conta/acessos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/minha-conta/acessos">> = Specific
  const handler = {} as typeof import("../../src/app/minha-conta/acessos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/minha-conta/notificacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/minha-conta/notificacoes">> = Specific
  const handler = {} as typeof import("../../src/app/minha-conta/notificacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/minha-conta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/minha-conta">> = Specific
  const handler = {} as typeof import("../../src/app/minha-conta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/minha-conta/seguranca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/minha-conta/seguranca">> = Specific
  const handler = {} as typeof import("../../src/app/minha-conta/seguranca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacional/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacional/clientes">> = Specific
  const handler = {} as typeof import("../../src/app/operacional/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacional/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacional/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/operacional/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacional/geolocalizacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacional/geolocalizacao">> = Specific
  const handler = {} as typeof import("../../src/app/operacional/geolocalizacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacional/os/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacional/os">> = Specific
  const handler = {} as typeof import("../../src/app/operacional/os/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacional/preventivas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacional/preventivas">> = Specific
  const handler = {} as typeof import("../../src/app/operacional/preventivas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacional/roteiro-tecnico/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacional/roteiro-tecnico">> = Specific
  const handler = {} as typeof import("../../src/app/operacional/roteiro-tecnico/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacional/servicos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacional/servicos/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/operacional/servicos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacional/servicos/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacional/servicos/configuracoes">> = Specific
  const handler = {} as typeof import("../../src/app/operacional/servicos/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operacional/servicos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operacional/servicos">> = Specific
  const handler = {} as typeof import("../../src/app/operacional/servicos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orcamento/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orcamento/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/orcamento/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orcamento/painel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orcamento/painel">> = Specific
  const handler = {} as typeof import("../../src/app/orcamento/painel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ordens-servico/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ordens-servico/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/ordens-servico/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ordens-servico/importacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ordens-servico/importacao">> = Specific
  const handler = {} as typeof import("../../src/app/ordens-servico/importacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ordens-servico/laboratorio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ordens-servico/laboratorio">> = Specific
  const handler = {} as typeof import("../../src/app/ordens-servico/laboratorio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ordens-servico/painel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ordens-servico/painel">> = Specific
  const handler = {} as typeof import("../../src/app/ordens-servico/painel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal-chamados/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal-chamados">> = Specific
  const handler = {} as typeof import("../../src/app/portal-chamados/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/propostas/auditoria-faturamento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propostas/auditoria-faturamento">> = Specific
  const handler = {} as typeof import("../../src/app/propostas/auditoria-faturamento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/propostas/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propostas/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/propostas/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/propostas/importacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propostas/importacao">> = Specific
  const handler = {} as typeof import("../../src/app/propostas/importacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/propostas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propostas">> = Specific
  const handler = {} as typeof import("../../src/app/propostas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/propostas/painel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propostas/painel">> = Specific
  const handler = {} as typeof import("../../src/app/propostas/painel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/redefinir-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/redefinir-senha">> = Specific
  const handler = {} as typeof import("../../src/app/redefinir-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solicitacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solicitacoes">> = Specific
  const handler = {} as typeof import("../../src/app/solicitacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/trocar-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trocar-senha">> = Specific
  const handler = {} as typeof import("../../src/app/trocar-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vistoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vistoria">> = Specific
  const handler = {} as typeof import("../../src/app/vistoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/administrativo/contratos/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/administrativo/contratos/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/administrativo/contratos/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/access-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/access-history">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/access-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/refresh">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clima/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clima">> = Specific
  const handler = {} as typeof import("../../src/app/api/clima/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/compras/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compras/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/compras/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/compras/importacao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compras/importacao">> = Specific
  const handler = {} as typeof import("../../src/app/api/compras/importacao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard-tv/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard-tv/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard-tv/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/estoque-logistica/importacao-pedidos/executar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque-logistica/importacao-pedidos/executar">> = Specific
  const handler = {} as typeof import("../../src/app/api/estoque-logistica/importacao-pedidos/executar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/estoque-logistica/importacao-pedidos/previa/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque-logistica/importacao-pedidos/previa">> = Specific
  const handler = {} as typeof import("../../src/app/api/estoque-logistica/importacao-pedidos/previa/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/estoque-logistica/novas-propostas/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque-logistica/novas-propostas/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/estoque-logistica/novas-propostas/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/estoque-logistica/roteiro-entrega/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque-logistica/roteiro-entrega/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/estoque-logistica/roteiro-entrega/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/estoque-logistica/roteiro-entrega/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/estoque-logistica/roteiro-entrega">> = Specific
  const handler = {} as typeof import("../../src/app/api/estoque-logistica/roteiro-entrega/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/auditoria/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/auditoria/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/auditoria/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/auditoria/filtros/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/auditoria/filtros">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/auditoria/filtros/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/auditoria/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/auditoria">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/auditoria/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/cadastros/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/cadastros/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/cadastros/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/configuracao-email/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/configuracao-email/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/configuracao-email/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/notificacoes/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/notificacoes/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/notificacoes/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/perfis/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/perfis/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/perfis/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/perfis/permissoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/perfis/permissoes">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/perfis/permissoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/perfis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/perfis">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/perfis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/sla-os/feriados/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/sla-os/feriados/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/sla-os/feriados/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/sla-os/horarios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/sla-os/horarios">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/sla-os/horarios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/sla-os/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/sla-os">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/sla-os/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/tipos-proposta/[tipo]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/tipos-proposta/[tipo]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/tipos-proposta/[tipo]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/tipos-proposta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/tipos-proposta">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/tipos-proposta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/usuarios/[id]/auditoria/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/usuarios/[id]/auditoria">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/usuarios/[id]/auditoria/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/usuarios/[id]/redefinir-senha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/usuarios/[id]/redefinir-senha">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/usuarios/[id]/redefinir-senha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/usuarios/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/usuarios/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/usuarios/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/usuarios/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/usuarios/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/usuarios/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/usuarios/perfis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/usuarios/perfis">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/usuarios/perfis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/usuarios/pessoas-disponiveis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/usuarios/pessoas-disponiveis">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/usuarios/pessoas-disponiveis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ferramentas/usuarios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ferramentas/usuarios">> = Specific
  const handler = {} as typeof import("../../src/app/api/ferramentas/usuarios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/financeiro/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/financeiro/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/financeiro/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/grandes-projetos/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/grandes-projetos/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/grandes-projetos/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/grandes-projetos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/grandes-projetos">> = Specific
  const handler = {} as typeof import("../../src/app/api/grandes-projetos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional-upload/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional-upload/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional-upload/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/geolocalizacao/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/geolocalizacao/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/geolocalizacao/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/notificacoes-obra/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/notificacoes-obra/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/notificacoes-obra/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/os/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/os/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/os/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/os/filtros/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/os/filtros">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/os/filtros/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/os/indicadores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/os/indicadores">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/os/indicadores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/os/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/os">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/os/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/os/sincronizacoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/os/sincronizacoes">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/os/sincronizacoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/os/sincronizacoes/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/os/sincronizacoes/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/os/sincronizacoes/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/roteiro/excel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/roteiro/excel">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/roteiro/excel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/operacional/roteiro/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operacional/roteiro/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/operacional/roteiro/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orcamentos/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orcamentos/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/orcamentos/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ordens-servico/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ordens-servico/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ordens-servico/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ordens-servico/importacao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ordens-servico/importacao">> = Specific
  const handler = {} as typeof import("../../src/app/api/ordens-servico/importacao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/propostas/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/propostas/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/propostas/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/propostas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/propostas">> = Specific
  const handler = {} as typeof import("../../src/app/api/propostas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/solicitacoes/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/solicitacoes/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/solicitacoes/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/usuarios/me/notificacoes/[id]/lida/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usuarios/me/notificacoes/[id]/lida">> = Specific
  const handler = {} as typeof import("../../src/app/api/usuarios/me/notificacoes/[id]/lida/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/usuarios/me/notificacoes/marcar-todas-lidas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usuarios/me/notificacoes/marcar-todas-lidas">> = Specific
  const handler = {} as typeof import("../../src/app/api/usuarios/me/notificacoes/marcar-todas-lidas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/usuarios/me/notificacoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usuarios/me/notificacoes">> = Specific
  const handler = {} as typeof import("../../src/app/api/usuarios/me/notificacoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/usuarios/me/preferencias-notificacao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usuarios/me/preferencias-notificacao">> = Specific
  const handler = {} as typeof import("../../src/app/api/usuarios/me/preferencias-notificacao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/dp-rh/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dp-rh">> = Specific
  const handler = {} as typeof import("../../src/app/dp-rh/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/financeiro/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/financeiro">> = Specific
  const handler = {} as typeof import("../../src/app/financeiro/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
