import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../database/prisma.service';
import { GpPageDto, GpRiskDto, GpTeamDto, GpVisitDto } from './dto/gp-governanca.dto';
type Actor={id?:string;nome:string}; type Kind='visit'|'team'|'risk';
@Injectable() export class GrandesProjetosGovernancaService {
 constructor(private readonly db:PrismaService){}
 private json(value:any):any { if(typeof value==='bigint') return value.toString(); if(Array.isArray(value)) return value.map(v=>this.json(v)); if(value&&typeof value==='object') return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,this.json(v)])); return value; }
 private model(tx:any,k:Kind){ return k==='visit'?tx.gp_visita:k==='team'?tx.gp_projeto_equipe:tx.gp_risco; }
 private async project(id:number){ const p=await this.db.gp_projeto.findFirst({where:{id,excluido_em:null}}); if(!p) throw new NotFoundException('Projeto não encontrado'); }
 private async audit(tx:any,a:Actor,e:string,id:bigint,acao:string,before:any,after:any){ await tx.auditoria.create({data:{usuarioId:a.id||null,entidade:e,entidadeId:id.toString(),acao,dadosAntes:this.json(before),dadosDepois:this.json(after)}}); }
 async list(k:Kind,pid:number,q:GpPageDto){ await this.project(pid); const m=this.model(this.db,k); const where={projeto_id:pid,excluido_em:null}; const [total,itens]=await this.db.$transaction([m.count({where}),m.findMany({where,orderBy:{id:'desc'},skip:(q.pagina-1)*q.limite,take:q.limite})]); return this.json({itens,paginacao:{pagina:q.pagina,limite:q.limite,total,paginas:Math.max(1,Math.ceil(total/q.limite))}}); }
 async save(k:Kind,pid:number,id:bigint|null,b:any,a:Actor){ await this.project(pid); if(k==='visit'&&b.dataFim&&new Date(b.dataFim)<new Date(b.dataInicio)) throw new BadRequestException('Data final anterior à inicial'); if(k==='team'&&b.vigenciaFim&&b.vigenciaInicio&&new Date(b.vigenciaFim)<new Date(b.vigenciaInicio)) throw new BadRequestException('Vigência final anterior à inicial'); if(k==='visit'&&b.osId){ const os=await this.db.gp_os.findFirst({where:{id:b.osId,projeto_id:pid,excluido_em:null}}); if(!os) throw new BadRequestException('OS não pertence ao projeto'); }
  return this.db.$transaction(async tx=>{ const m=this.model(tx,k); const before=id?await m.findFirst({where:{id,projeto_id:pid,excluido_em:null}}):null; if(id&&!before) throw new NotFoundException('Registro não encontrado'); if(id&&b.versao!==before.versao) throw new BadRequestException('Registro alterado por outro usuário'); const data=this.data(k,b); const after=id?await m.update({where:{id},data:{...data,versao:{increment:1}}}):await m.create({data:{...data,projeto_id:pid}}); await this.audit(tx,a,`gp_${k}`,after.id,id?'ATUALIZAR':'CRIAR',before,after); return this.json(after); }); }
 async remove(k:Kind,pid:number,id:bigint,versao:number,motivo:string,a:Actor){ return this.db.$transaction(async tx=>{ const m=this.model(tx,k); const before=await m.findFirst({where:{id,projeto_id:pid,excluido_em:null}}); if(!before) throw new NotFoundException('Registro não encontrado'); if(before.versao!==versao) throw new BadRequestException('Registro alterado por outro usuário'); const after=await m.update({where:{id},data:{excluido_em:new Date(),excluido_por_id:a.id||null,motivo_exclusao:motivo,versao:{increment:1}}}); await this.audit(tx,a,`gp_${k}`,id,'EXCLUIR_LOGICO',before,after); return this.json(after); }); }
 private data(k:Kind,b:any){ if(k==='visit') return {os_id:b.osId,tecnico:b.tecnico,funcionario_id:b.funcionarioId,data_inicio:new Date(b.dataInicio),data_fim:b.dataFim?new Date(b.dataFim):null,objetivo:b.objetivo,atividade_realizada:b.atividadeRealizada,pendencias:b.pendencias,proxima_acao:b.proximaAcao,latitude:b.latitude,longitude:b.longitude,custo:b.custo,status:b.status}; if(k==='team') return {funcionario_id:b.funcionarioId,nome:b.nome,funcao:b.funcao,vigencia_inicio:b.vigenciaInicio?new Date(b.vigenciaInicio):null,vigencia_fim:b.vigenciaFim?new Date(b.vigenciaFim):null,custo_gerencial_mensal:b.custoGerencialMensal}; return {titulo:b.titulo,descricao:b.descricao,impacto:b.impacto,probabilidade:b.probabilidade,criticidade:b.criticidade,responsavel:b.responsavel,prazo:b.prazo?new Date(b.prazo):null,status:b.status,plano_acao:b.planoAcao}; }
}
