"use client";
import { ChevronDown, ChevronUp, RefreshCw, Search } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
type Item={id:string;produtoCodigo:string;produtoDescricao:string;quantidadeNecessaria:string;quantidadeComprada:string;quantidadeRecebida:string;statusItem:string};
type Proposal={id:string;propostaNumero:string;clienteNome?:string|null;local?:string|null;statusCompra:string;itens:Item[];totais:{itens:number;necessario:string;comprado:string;recebido:string}};
function n(v:string){return Number(v||0)}function pct(a:string,b:string){const total=n(b);return total?Math.min(100,Math.round(n(a)/total*100)):0}
export function PurchasesPanel(){const[data,setData]=useState<Proposal[]>([]);const[search,setSearch]=useState("");const[status,setStatus]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[open,setOpen]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");const q=new URLSearchParams();if(search.trim())q.set("busca",search.trim());if(status)q.set("status",status);try{const r=await fetch(`/api/compras/painel?${q}`,{cache:"no-store"});const p:unknown=await r.json();if(!r.ok)throw new Error(typeof p==="object"&&p&&"message" in p?String(p.message):"Falha ao carregar painel");setData(p as Proposal[])}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar painel")}finally{setLoading(false)}},[search,status]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),search?350:0);return()=>window.clearTimeout(t)},[load,search,status]);
 return <main className="mx-auto max-w-[1600px] space-y-5"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-semibold text-red-600">Compras</p><h1 className="text-3xl font-bold">Painel operacional</h1><p className="mt-1 text-sm text-slate-500">Acompanhe necessidades, compras e recebimentos por proposta.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Atualizar</button></header>
 <section className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_260px] dark:border-slate-800 dark:bg-slate-950"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Proposta, cliente ou local" className="w-full rounded-xl border bg-transparent py-2.5 pl-10 pr-3 dark:border-slate-700"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border bg-transparent px-3 py-2.5 dark:border-slate-700"><option value="">Todos os status</option>{["NAO_INICIADA","PARCIAL","COMPRADA","RECEBIDA_PARCIAL","RECEBIDA_TOTAL","CANCELADA"].map(x=><option key={x}>{x}</option>)}</select></section>
 {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}
 <section className="space-y-3">{!loading&&!data.length&&<div className="rounded-2xl border p-10 text-center text-slate-500">Nenhuma proposta encontrada.</div>}{data.map(p=>{const progress=pct(p.totais.recebido,p.totais.necessario);return <article key={p.id} className="overflow-hidden rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-950"><button type="button" onClick={()=>setOpen(open===p.id?null:p.id)} className="grid w-full gap-4 p-4 text-left lg:grid-cols-[140px_1fr_150px_220px_30px] lg:items-center"><strong>#{p.propostaNumero}</strong><span><b>{p.clienteNome??"Cliente não informado"}</b><small className="block text-slate-500">{p.local??"Local não informado"}</small></span><span className="text-sm">{p.statusCompra}</span><span><span className="flex justify-between text-xs"><b>{progress}% recebido</b><span>{p.totais.itens} itens</span></span><span className="mt-2 block h-2 overflow-hidden rounded-full bg-slate-200"><i className="block h-full bg-emerald-500" style={{width:`${progress}%`}}/></span></span>{open===p.id?<ChevronUp/>:<ChevronDown/>}</button>{open===p.id&&<div className="overflow-x-auto border-t dark:border-slate-800"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left dark:bg-slate-900"><tr>{["Código","Produto","Necessário","Comprado","Recebido","Status"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y dark:divide-slate-800">{p.itens.map(i=><tr key={i.id}><td className="px-4 py-3">{i.produtoCodigo}</td><td className="min-w-80 px-4 py-3">{i.produtoDescricao}</td><td className="px-4 py-3">{n(i.quantidadeNecessaria).toLocaleString("pt-BR")}</td><td className="px-4 py-3">{n(i.quantidadeComprada).toLocaleString("pt-BR")}</td><td className="px-4 py-3">{n(i.quantidadeRecebida).toLocaleString("pt-BR")}</td><td className="px-4 py-3">{i.statusItem}</td></tr>)}</tbody></table></div>}</article>})}</section></main>}
