"use client";
import { AlertTriangle, Boxes, CheckCircle2, Clock3, RefreshCw, ShoppingCart, Truck } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Group={statusCompra?:string;statusItem?:string;status?:string;_count:{_all:number};_sum?:{quantidadeNecessaria?:string|null;quantidadeComprada?:string|null;quantidadeRecebida?:string|null;valorTotal?:string|null}};
type Dashboard={propostas:Group[];itens:Group[];pedidos:Group[];recebimentos:Group[];pedidosAtrasados:number;atualizadoEm:string};
const labels:Record<string,string>={NAO_INICIADA:"Não iniciada",PARCIAL:"Parcial",COMPRADA:"Comprada",RECEBIDA_PARCIAL:"Recebida parcial",RECEBIDA_TOTAL:"Recebida total",CANCELADA:"Cancelada",PENDENTE:"Pendente",COMPRA_PARCIAL:"Compra parcial",COMPRADO:"Comprado",RECEBIDO_PARCIAL:"Recebido parcial",RECEBIDO_TOTAL:"Recebido total"};
function messageOf(v:unknown){if(v&&typeof v==="object"&&"message" in v){const m=(v as {message?:string|string[]}).message;return Array.isArray(m)?m.join(". "):m}return undefined}
function count(groups:Group[],status:string){return groups.find(x=>(x.statusCompra??x.statusItem??x.status)===status)?._count._all??0}
export function PurchasesDashboard(){const[data,setData]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/compras/dashboard",{cache:"no-store"});const p:unknown=await r.json();if(!r.ok)throw new Error(messageOf(p)??"Falha ao carregar dashboard");setData(p as Dashboard)}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar dashboard")}finally{setLoading(false)}},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t)},[load]);
 const chart=useMemo(()=>data?.propostas.map(x=>({nome:labels[x.statusCompra??""]??x.statusCompra,quantidade:x._count._all}))??[],[data]);
 const cards=[{label:"Propostas pendentes",value:count(data?.propostas??[],"NAO_INICIADA"),icon:Clock3,color:"amber"},{label:"Compras em andamento",value:count(data?.propostas??[],"PARCIAL"),icon:ShoppingCart,color:"blue"},{label:"Totalmente compradas",value:count(data?.propostas??[],"COMPRADA"),icon:CheckCircle2,color:"emerald"},{label:"Recebidas",value:count(data?.propostas??[],"RECEBIDA_TOTAL"),icon:Boxes,color:"violet"},{label:"Pedidos atrasados",value:data?.pedidosAtrasados??0,icon:AlertTriangle,color:"red"},{label:"Recebimentos",value:(data?.recebimentos??[]).reduce((a,x)=>a+x._count._all,0),icon:Truck,color:"slate"}] as const;
 return <main className="mx-auto max-w-[1600px] space-y-6"><header className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-red-950 p-6 text-white shadow-xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-red-300">Compras</p><h1 className="mt-2 text-3xl font-bold">Centro de controle de compras</h1><p className="mt-2 text-sm text-slate-300">Necessidades, pedidos, fornecedores e recebimentos em uma visão consolidada.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-4 py-2.5 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Atualizar</button></div></header>
 {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(c=><article key={c.label} className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{c.label}</p><p className="mt-2 text-3xl font-bold">{loading?"…":c.value.toLocaleString("pt-BR")}</p></div><c.icon className="h-5 w-5 text-red-600"/></div></article>)}</section>
 <section className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><article className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><h2 className="font-bold">Propostas por fase de compra</h2><div className="mt-4 h-80">{chart.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={chart} accessibilityLayer><CartesianGrid strokeDasharray="4 6" vertical={false}/><XAxis dataKey="nome"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="quantidade" fill="#dc2626" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-slate-500">Sem dados</div>}</div></article><article className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><h2 className="font-bold">Situação dos materiais</h2><div className="mt-4 space-y-3">{(data?.itens??[]).map(x=>{const s=x.statusItem??"";return <div key={s} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 dark:bg-slate-900"><span>{labels[s]??s}</span><strong>{x._count._all.toLocaleString("pt-BR")}</strong></div>})}</div></article></section>
 <p className="text-xs text-slate-500">Atualizado em {data?new Date(data.atualizadoEm).toLocaleString("pt-BR"):"—"}</p></main>}
