var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/ordens-servico/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1x4kqzc._.js")
R.c("server/chunks/ssr/node_modules_next_17sz44y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0juh33g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jj_y02._.js")
R.c("server/chunks/ssr/[root-of-the-server]__112mz-6._.js")
R.c("server/chunks/ssr/src_06lubcf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_ordens-servico_dashboard_page_actions_0wvum3h.js")
R.m(69552)
module.exports=R.m(69552).exports
