"use client";

import { Check, Search, X } from "lucide-react";
import { FormEvent, KeyboardEvent, useEffect, useId, useState } from "react";

type Client={id:string;codigo?:string|null;razaoSocial:string;nomeFantasia?:string|null;cnpj?:string|null;municipio?:string|null;uf?:string|null};
type Proposal={id:number;numero:string;titulo?:string|null;status:string;tipo?:string|null;local?:string|null;valProposta?:string|number|null};
type Page<T>={itens:T[];paginacao:{pagina:number;limite:number;total:number;totalPaginas:number}};
const stages=["CADASTRO_INICIAL","MINUTA_EM_ELABORACAO","REVISAO_INTERNA","ENVIADA_AO_CLIENTE","EM_NEGOCIACAO","AJUSTES_SOLICITADOS","APROVADA_INTERNAMENTE","AGUARDANDO_ASSINATURA","EM_ASSINATURA","ASSINADA","CANCELADA"];
const statuses=["RASCUNHO","ATIVO","SUSPENSO","ENCERRADO","RESCINDIDO","CANCELADO"];
const initial={clienteId:"",titulo:"",tipo:"",objeto:"",etapa:"CADASTRO_INICIAL",status:"RASCUNHO",vigenciaInicio:"",vigenciaFim:"",propostaIds:[] as number[]};
function message(v:unknown){if(v&&typeof v==="object"&&"message" in v){const m=(v as {message?:string|string[]}).message;return Array.isArray(m)?m.join(". "):m||"Não foi possível concluir."}return "Não foi possível concluir."}
async function get<T>(path:string){const r=await fetch(path,{cache:"no-store"});const d:unknown=await r.json().catch(()=>null);if(!r.ok)throw new Error(message(d));return d as T}
const clientLabel=(c:Client)=>[c.codigo?`Cód. ${c.codigo}`:"",c.razaoSocial,c.nomeFantasia,c.cnpj].filter(Boolean).join(" · ");

export function ContractCreateDialog({onClose,onCreated}:{onClose:()=>void;onCreated:()=>Promise<void>}){
 const listId=useId();
 const [form,setForm]=useState(initial),[clientSearch,setClientSearch]=useState(""),[clients,setClients]=useState<Client[]>([]),[selectedClient,setSelectedClient]=useState<Client|null>(null);
 const [clientOpen,setClientOpen]=useState(false),[clientLoading,setClientLoading]=useState(false),[active,setActive]=useState(-1);
 const [proposalSearch,setProposalSearch]=useState(""),[proposals,setProposals]=useState<Proposal[]>([]),[proposalLoading,setProposalLoading]=useState(false);
 const [saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const term=clientSearch.trim();if(term.length<2&&!/^\d+$/.test(term))return;const timer=window.setTimeout(()=>{setClientLoading(true);void get<Page<Client>>(`/api/administrativo/contratos/opcoes/clientes?busca=${encodeURIComponent(term)}&pagina=1&limite=30`).then(d=>{setClients(d.itens);setClientOpen(true);setActive(-1)}).catch(e=>setError(e instanceof Error?e.message:"Falha ao buscar clientes.")).finally(()=>setClientLoading(false))},300);return()=>window.clearTimeout(timer)},[clientSearch]);
 useEffect(()=>{if(!selectedClient)return;const timer=window.setTimeout(()=>{setProposalLoading(true);void get<Page<Proposal>>(`/api/administrativo/contratos/opcoes/propostas?clienteId=${selectedClient.id}&busca=${encodeURIComponent(proposalSearch.trim())}&pagina=1&limite=50`).then(d=>setProposals(d.itens)).catch(e=>setError(e instanceof Error?e.message:"Falha ao buscar propostas.")).finally(()=>setProposalLoading(false))},250);return()=>window.clearTimeout(timer)},[selectedClient,proposalSearch]);
 function chooseClient(c:Client){setSelectedClient(c);setForm(f=>({...f,clienteId:c.id,propostaIds:[]}));setClientSearch(clientLabel(c));setClientOpen(false);setProposals([]);setProposalSearch("")}
 function keyboard(e:KeyboardEvent<HTMLInputElement>){if(!clientOpen||!clients.length)return;if(e.key==="ArrowDown"){e.preventDefault();setActive(i=>Math.min(i+1,clients.length-1))}else if(e.key==="ArrowUp"){e.preventDefault();setActive(i=>Math.max(i-1,0))}else if(e.key==="Enter"&&active>=0){e.preventDefault();chooseClient(clients[active])}else if(e.key==="Escape"){setClientOpen(false)}}
 function toggleProposal(id:number){setForm(f=>({...f,propostaIds:f.propostaIds.includes(id)?f.propostaIds.filter(x=>x!==id):[...f.propostaIds,id]}))}
 async function submit(e:FormEvent){e.preventDefault();if(!selectedClient){setError("Selecione um cliente válido nos resultados da pesquisa.");return}setSaving(true);setError("");try{const r=await fetch("/api/administrativo/contratos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,vigenciaInicio:form.vigenciaInicio||undefined,vigenciaFim:form.vigenciaFim||undefined})});const d:unknown=await r.json().catch(()=>null);if(!r.ok)throw new Error(message(d));await onCreated();onClose()}catch(e){setError(e instanceof Error?e.message:"Falha ao criar contrato.")}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="max-h-[94vh] w-full max-w-4xl overflow-auto rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-950"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Novo contrato</h2><p className="text-sm text-slate-500">Localize o cliente e associe as propostas relacionadas.</p></div><button type="button" onClick={onClose} aria-label="Fechar"><X/></button></div>{error&&<div role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="mt-5 space-y-5"><section className="rounded-2xl border p-4"><h3 className="font-bold">1. Cliente</h3><label className="mt-3 block text-sm font-medium" htmlFor="contract-client-search">CNPJ, razão social, fantasia ou código</label><div className="relative mt-1"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input id="contract-client-search" role="combobox" aria-autocomplete="list" aria-expanded={clientOpen} aria-controls={listId} aria-activedescendant={active>=0?`${listId}-${active}`:undefined} autoComplete="off" value={clientSearch} onKeyDown={keyboard} onChange={e=>{setClientSearch(e.target.value);setSelectedClient(null);setClients([]);setProposals([]);setForm(f=>({...f,clienteId:"",propostaIds:[]}));setClientOpen(true)}} placeholder="Digite ao menos 2 caracteres" className="w-full rounded-xl border bg-transparent py-3 pl-10 pr-3"/>{clientOpen&&<ul id={listId} role="listbox" className="absolute z-20 mt-1 max-h-64 w-full overflow-auto rounded-xl border bg-white shadow-xl dark:bg-slate-950">{clientLoading?<li className="p-3 text-sm">Buscando...</li>:clients.map((c,i)=><li id={`${listId}-${i}`} key={c.id} role="option" aria-selected={selectedClient?.id===c.id} onMouseDown={()=>chooseClient(c)} className={`cursor-pointer border-b p-3 text-sm last:border-0 dark:border-slate-800 ${active===i?"bg-red-50 dark:bg-red-950/30":""}`}><b>{c.razaoSocial}</b><p className="text-xs text-slate-500">{[c.codigo?`Código ${c.codigo}`:null,c.nomeFantasia,c.cnpj,[c.municipio,c.uf].filter(Boolean).join("/")].filter(Boolean).join(" · ")}</p></li>)}{!clientLoading&&!clients.length&&clientSearch.trim().length>=2&&<li className="p-3 text-sm text-slate-500">Nenhum cliente encontrado.</li>}</ul>}</div>{selectedClient&&<div className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><Check className="mr-2 inline" size={16}/><b>{selectedClient.razaoSocial}</b> · {selectedClient.cnpj||"CNPJ não informado"}</div>}</section>
 <section className={`rounded-2xl border p-4 ${!selectedClient?"opacity-60":""}`}><h3 className="font-bold">2. Propostas associadas</h3><p className="text-xs text-slate-500">Selecione uma ou mais propostas do cliente. A associação é opcional.</p><input disabled={!selectedClient} value={proposalSearch} onChange={e=>setProposalSearch(e.target.value)} placeholder="Buscar por número, título, local ou status" className="mt-3 w-full rounded-xl border bg-transparent p-3"/><div className="mt-3 max-h-60 space-y-2 overflow-auto">{proposalLoading&&<p className="text-sm">Buscando propostas...</p>}{proposals.map(p=><label key={p.id} className="flex cursor-pointer gap-3 rounded-xl border p-3"><input type="checkbox" checked={form.propostaIds.includes(p.id)} onChange={()=>toggleProposal(p.id)}/><span><b>Proposta {p.numero}</b><span className="ml-2 rounded-full bg-slate-100 px-2 py-1 text-xs dark:bg-slate-800">{p.status}</span><p className="text-xs text-slate-500">{[p.titulo,p.local,p.tipo].filter(Boolean).join(" · ")||"Sem detalhes adicionais"}</p></span></label>)}{selectedClient&&!proposalLoading&&!proposals.length&&<p className="text-sm text-slate-500">Nenhuma proposta encontrada para este cliente.</p>}</div>{form.propostaIds.length>0&&<p className="mt-2 text-sm font-semibold text-red-600">{form.propostaIds.length} proposta(s) selecionada(s)</p>}</section>
 <section className="grid gap-4 rounded-2xl border p-4 md:grid-cols-2"><h3 className="md:col-span-2 font-bold">3. Dados do contrato</h3><label>Título<input required maxLength={300} value={form.titulo} onChange={e=>setForm(f=>({...f,titulo:e.target.value}))} className="mt-1 w-full rounded-xl border bg-transparent p-3"/></label><label>Tipo<input maxLength={100} value={form.tipo} onChange={e=>setForm(f=>({...f,tipo:e.target.value}))} className="mt-1 w-full rounded-xl border bg-transparent p-3"/></label><label>Etapa<select value={form.etapa} onChange={e=>setForm(f=>({...f,etapa:e.target.value}))} className="mt-1 w-full rounded-xl border bg-transparent p-3">{stages.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))} className="mt-1 w-full rounded-xl border bg-transparent p-3">{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Início<input type="date" value={form.vigenciaInicio} onChange={e=>setForm(f=>({...f,vigenciaInicio:e.target.value}))} className="mt-1 w-full rounded-xl border bg-transparent p-3"/></label><label>Fim<input type="date" value={form.vigenciaFim} onChange={e=>setForm(f=>({...f,vigenciaFim:e.target.value}))} className="mt-1 w-full rounded-xl border bg-transparent p-3"/></label><label className="md:col-span-2">Objeto<textarea maxLength={10000} value={form.objeto} onChange={e=>setForm(f=>({...f,objeto:e.target.value}))} className="mt-1 min-h-28 w-full rounded-xl border bg-transparent p-3"/></label></section></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border px-5 py-2.5">Cancelar</button><button disabled={saving||!selectedClient} className="rounded-xl bg-red-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{saving?"Salvando...":"Criar contrato"}</button></div></form></div>;
}
