"use client";
import { ChevronLeft, ChevronRight, Download, Printer, RefreshCw, Search } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Item={expedienteId:string;nome:string;unidade:string|null;cargo:string|null;status:string;origem:string;iniciadoEm:string;finalizadoEm:string|null;duracaoMinutos:number;capturas:number;bateriaMinima:number|null;ultimoEndereco:string|null};
type Data={itens:Item[];paginacao:{pagina:number;limite:number;total:number;totalPaginas:number};indicadores:{jornadas:number;capturas:number;emAberto:number;duracaoMinutos:number};geradoEm:string};
const today=()=>new Date().toISOString().slice(0,10); const ago=()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10);
const fmt=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR"):"Em andamento"; const duration=(m:number)=>`${Math.floor(m/60)}h ${Math.round(m%60)}min`;
export function GeolocationReport(){
 const [q,setQ]=useState({inicio:ago(),fim:today(),busca:"",status:"",pagina:1,limite:25}); const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams(Object.entries(q).filter(([, value]) => String(value).trim() !== "").map(([key, value]) => [key, String(value)]));const r=await fetch(`/api/operacional/geolocalizacao/relatorio?${p}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message||"Falha ao carregar relatório");setData(j)}catch(e){setError(e instanceof Error?e.message:"Falha inesperada")}finally{setLoading(false)}},[q]);
 useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t)},[load]);
 function submit(e:FormEvent){e.preventDefault();setQ(x=>({...x,pagina:1}))}
 function csv(){if(!data)return;const rows=[["Expediente","Colaborador","Unidade","Cargo","Status","Início","Fim","Duração (min)","Capturas","Bateria mínima","Último endereço"],...data.itens.map(x=>[x.expedienteId,x.nome,x.unidade??"",x.cargo??"",x.status,fmt(x.iniciadoEm),fmt(x.finalizadoEm),x.duracaoMinutos,x.capturas,x.bateriaMinima??"",x.ultimoEndereco??""])];const text="\ufeff"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));a.download=`geolocalizacao-${q.inicio}-${q.fim}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const i=data?.indicadores;
 return <main className="space-y-5 print:space-y-3"><header className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-red-950 p-6 text-white shadow-xl"><div className="flex flex-col gap-4 lg:flex-row lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-red-300">Geolocalização</p><h1 className="mt-2 text-3xl font-bold">Relatório de jornadas</h1><p className="mt-2 text-sm text-slate-300">Consolidação autorizada de expedientes e telemetria.</p></div><div className="flex gap-2 print:hidden"><button onClick={()=>void load()} className="rounded-xl border border-white/20 px-4 py-2"><RefreshCw className={`inline h-4 w-4 ${loading?"animate-spin":""}`}/> Atualizar</button><button onClick={()=>window.print()} className="rounded-xl border border-white/20 px-4 py-2"><Printer className="inline h-4 w-4"/> Imprimir</button><button onClick={csv} className="rounded-xl bg-emerald-600 px-4 py-2"><Download className="inline h-4 w-4"/> CSV</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Jornadas",i?.jornadas??0],["Capturas na página",i?.capturas??0],["Em aberto na página",i?.emAberto??0],["Duração na página",duration(i?.duracaoMinutos??0)]].map(([a,b])=><div key={a} className="rounded-2xl bg-white/10 p-4"><p className="text-sm text-slate-300">{a}</p><strong className="text-2xl">{b}</strong></div>)}</div></header>
 <form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-950 md:grid-cols-5 print:hidden"><label className="text-sm">Início<input type="date" value={q.inicio} onChange={e=>setQ(x=>({...x,inicio:e.target.value,pagina:1}))} className="mt-1 w-full rounded-xl border bg-transparent p-2"/></label><label className="text-sm">Fim<input type="date" value={q.fim} min={q.inicio} onChange={e=>setQ(x=>({...x,fim:e.target.value,pagina:1}))} className="mt-1 w-full rounded-xl border bg-transparent p-2"/></label><label className="relative text-sm md:col-span-2">Buscar<Search className="absolute bottom-3 left-3 h-4 w-4 text-slate-400"/><input value={q.busca} onChange={e=>setQ(x=>({...x,busca:e.target.value}))} placeholder="Nome, cargo ou unidade" className="mt-1 w-full rounded-xl border bg-transparent p-2 pl-9"/></label><label className="text-sm">Status<select value={q.status} onChange={e=>setQ(x=>({...x,status:e.target.value,pagina:1}))} className="mt-1 w-full rounded-xl border bg-transparent p-2"><option value="">Todos</option><option>ATIVO</option><option>PAUSADO</option><option>FINALIZADO</option></select></label></form>
 {error&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}
 <section className="overflow-hidden rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-950"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left dark:bg-slate-900"><tr>{["Colaborador","Status","Início","Fim","Duração","Capturas","Bateria","Último endereço"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y dark:divide-slate-800">{loading?<tr><td colSpan={8} className="p-10 text-center">Carregando...</td></tr>:data?.itens.map(x=><tr key={x.expedienteId}><td className="px-4 py-3"><b>{x.nome}</b><small className="block text-slate-500">{x.cargo??"Cargo não informado"} · {x.unidade??"Unidade não informada"}</small></td><td className="px-4 py-3">{x.status}</td><td className="whitespace-nowrap px-4 py-3">{fmt(x.iniciadoEm)}</td><td className="whitespace-nowrap px-4 py-3">{fmt(x.finalizadoEm)}</td><td className="px-4 py-3">{duration(x.duracaoMinutos)}</td><td className="px-4 py-3">{x.capturas}</td><td className="px-4 py-3">{x.bateriaMinima==null?"—":`${x.bateriaMinima}%`}</td><td className="max-w-xs px-4 py-3">{x.ultimoEndereco??"—"}</td></tr>)}{!loading&&!data?.itens.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">Nenhuma jornada encontrada.</td></tr>}</tbody></table></div><footer className="flex items-center justify-between border-t p-4 text-sm print:hidden"><span>{data?.paginacao.total??0} registros · Página {data?.paginacao.pagina??1} de {data?.paginacao.totalPaginas??1}</span><div className="flex gap-2"><button disabled={loading||(data?.paginacao.pagina??1)<=1} onClick={()=>setQ(x=>({...x,pagina:x.pagina-1}))} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft/></button><button disabled={loading||(data?.paginacao.pagina??1)>=(data?.paginacao.totalPaginas??1)} onClick={()=>setQ(x=>({...x,pagina:x.pagina+1}))} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight/></button></div></footer></section></main>
}
