import { Image,Pressable,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router,usePathname } from 'expo-router';
import { ReactNode } from 'react';
import { StatusBar } from 'expo-status-bar';
import { useAppTheme } from '../theme/use-app-theme';
import { useAuthStore } from '../stores/auth.store';
import { WeatherChip } from './weather-chip';
import { NotificationButton } from './notification-button';
export function MobileAppShell({title,subtitle,children}:{title:string;subtitle?:string;children:ReactNode}){const p=useAppTheme();const path=usePathname();const user=useAuthStore(s=>s.user) as {nome?:string;name?:string}|null;const initials=(user?.nome??user?.name??'U').split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();return <SafeAreaView style={[s.safe,{backgroundColor:p.background}]} edges={['top','bottom','left','right']}><StatusBar style={p.isDark?'light':'dark'}/><View style={[s.top,{backgroundColor:p.surface,borderColor:p.border}]}><Image source={p.isDark?require('../../assets/brand/logo_escuro.png'):require('../../assets/brand/logo_claro.png')} style={s.logo} resizeMode="contain"/><View style={s.topActions}><WeatherChip/><NotificationButton/><Pressable accessibilityRole="button" accessibilityLabel="Abrir meu perfil" onPress={()=>router.push('/meu-perfil')} style={[s.avatar,{backgroundColor:p.primary}]}><Text style={s.avatarText}>{initials}</Text></Pressable></View></View><View style={[s.heading,{backgroundColor:p.surface}]}><Text style={[s.title,{color:p.text}]}>{title}</Text>{subtitle?<Text style={[s.subtitle,{color:p.textMuted}]}>{subtitle}</Text>:null}</View><View style={s.content}>{children}</View><View style={[s.nav,{backgroundColor:p.nav,borderColor:p.border}]}><Nav active={path==='/dashboard'} label="Início" symbol="⌂" onPress={()=>router.replace('/dashboard')}/><Nav active={path.startsWith('/atividades')||path.startsWith('/os')||path.startsWith('/roteiro-entrega')} label="Atividades" symbol="▣" onPress={()=>router.push('/atividades')}/><Nav main label="Ação" symbol="+" onPress={()=>router.push('/atividades')}/><Nav active={path.startsWith('/notificacoes')} label="Alertas" symbol="!" onPress={()=>router.push('/notificacoes')}/><Nav active={path.startsWith('/meu-perfil')} label="Perfil" symbol="●" onPress={()=>router.push('/meu-perfil')}/></View></SafeAreaView>}
function Nav({label,symbol,onPress,active=false,main=false}:{label:string;symbol:string;onPress:()=>void;active?:boolean;main?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{selected:active}} onPress={onPress} style={[s.navItem,main&&s.main]}><View style={[s.navIcon,main&&s.mainIcon,active&&s.active]}><Text style={[s.symbol,main&&s.mainText]}>{symbol}</Text></View><Text style={[s.navLabel,active&&s.navLabelActive]}>{label}</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1},top:{height:64,paddingHorizontal:16,borderBottomWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{width:138,height:40},topActions:{flexDirection:'row',alignItems:'center',gap:8},weather:{height:34,borderRadius:10,paddingHorizontal:9,alignItems:'center',justifyContent:'center'},weatherText:{fontSize:9,fontWeight:'900'},iconButton:{width:34,height:34,borderRadius:10,alignItems:'center',justifyContent:'center'},iconText:{fontSize:15},avatar:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center'},avatarText:{color:'#FFF',fontSize:11,fontWeight:'900'},heading:{paddingHorizontal:18,paddingTop:12,paddingBottom:10},title:{fontSize:22,fontWeight:'900'},subtitle:{fontSize:12,marginTop:2},content:{flex:1},nav:{minHeight:70,borderTopWidth:1,paddingHorizontal:6,paddingTop:7,paddingBottom:8,flexDirection:'row'},navItem:{flex:1,alignItems:'center',justifyContent:'center'},navIcon:{width:32,height:28,borderRadius:10,alignItems:'center',justifyContent:'center'},active:{backgroundColor:'#FFFFFF22'},symbol:{color:'#D7E1EA',fontSize:17,fontWeight:'900'},navLabel:{color:'#AEBCCA',fontSize:9,fontWeight:'700',marginTop:3},navLabelActive:{color:'#FFF'},main:{marginTop:-25},mainIcon:{width:52,height:52,borderRadius:26,backgroundColor:'#C42032',borderWidth:4,borderColor:'#10243E'},mainText:{color:'#FFF',fontSize:26}});
