var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/ferramentas/notificacoes/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__05joz6i._.js")
R.c("server/chunks/ssr/node_modules_next_17sz44y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0juh33g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jj_y02._.js")
R.c("server/chunks/ssr/[root-of-the-server]__112mz-6._.js")
R.c("server/chunks/ssr/src_06lubcf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_ferramentas_notificacoes_page_actions_1jvdo5j.js")
R.m(7741)
module.exports=R.m(7741).exports
