'use client';
import { useEffect, useMemo, useState } from 'react';
type F={id:string;codigo:string;nome:string;razao_social?:string|null;nome_fantasia?:string|null;cnpj?:string|null;tipo_estabelecimento:string;inscricao_estadual?:string|null;inscricao_municipal?:string|null;cep?:string|null;logradouro?:string|null;numero?:string|null;complemento?:string|null;bairro?:string|null;cidade?:string|null;uf?:string|null;ativo:boolean};
type Form={codigo:string;nome:string;razaoSocial:string;nomeFantasia:string;cnpj:string;tipoEstabelecimento:string;inscricaoEstadual:string;inscricaoMunicipal:string;cep:string;logradouro:string;numero:string;complemento:string;bairro:string;cidade:string;uf:string;ativo:boolean};
type Errors=Partial<Record<keyof Form,string>>;
const empty:Form={codigo:'',nome:'',razaoSocial:'',nomeFantasia:'',cnpj:'',tipoEstabelecimento:'FILIAL',inscricaoEstadual:'',inscricaoMunicipal:'',cep:'',logradouro:'',numero:'',complemento:'',bairro:'',cidade:'',uf:'',ativo:true};
const digits=(v:string)=>v.replace(/\D/g,'');
const friendly=async(r:Response)=>{const raw=await r.text();try{const j=JSON.parse(raw) as {message?:string|string[]};return Array.isArray(j.message)?j.message.join(' '):j.message||'Não foi possível concluir a operação.'}catch{return raw||'Não foi possível concluir a operação.'}};
export function FiliaisManager(){
 const [rows,setRows]=useState<F[]>([]),[form,setForm]=useState<Form>({...empty}),[id,setId]=useState<string|null>(null),[msg,setMsg]=useState(''),[errors,setErrors]=useState<Errors>({}),[busy,setBusy]=useState(false),[consulting,setConsulting]=useState(false);
 const title=useMemo(()=>id?'Editar filial':'Nova filial',[id]);
 const load=async()=>{const r=await fetch('/api/financeiro/filiais');if(!r.ok)throw new Error(await friendly(r));setRows(await r.json() as F[])};
 useEffect(()=>{let active=true;const controller=new AbortController();fetch('/api/financeiro/filiais',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error(await friendly(r));return r.json() as Promise<F[]>}).then(data=>{if(active)setRows(data)}).catch(error=>{if(active&&error instanceof Error&&error.name!=='AbortError')setMsg(error.message)});return()=>{active=false;controller.abort()}},[]);
 const change=<K extends keyof Form>(k:K,v:Form[K])=>{setForm(current=>({...current,[k]:v}));setErrors(current=>({...current,[k]:undefined}));setMsg('')};
 const edit=(x:F)=>{setId(x.id);setErrors({});setMsg('');setForm({codigo:x.codigo||'',nome:x.nome||'',razaoSocial:x.razao_social||'',nomeFantasia:x.nome_fantasia||'',cnpj:x.cnpj||'',tipoEstabelecimento:x.tipo_estabelecimento||'FILIAL',inscricaoEstadual:x.inscricao_estadual||'',inscricaoMunicipal:x.inscricao_municipal||'',cep:x.cep||'',logradouro:x.logradouro||'',numero:x.numero||'',complemento:x.complemento||'',bairro:x.bairro||'',cidade:x.cidade||'',uf:x.uf||'',ativo:x.ativo});window.scrollTo({top:0,behavior:'smooth'})};
 const cancel=()=>{setId(null);setForm({...empty});setErrors({});setMsg('')};
 const validate=()=>{const e:Errors={};if(!form.codigo.trim())e.codigo='Informe o código da filial.';if(!form.nome.trim())e.nome='Informe o nome operacional.';if(form.cnpj&&digits(form.cnpj).length!==14)e.cnpj='O CNPJ deve ter 14 dígitos.';if(form.cep&&digits(form.cep).length!==8)e.cep='O CEP deve ter 8 dígitos.';if(form.uf&&form.uf.trim().length!==2)e.uf='Informe a UF com 2 letras.';setErrors(e);return !Object.keys(e).length};
 const consultCnpj=async()=>{if(digits(form.cnpj).length!==14){setErrors(e=>({...e,cnpj:'Informe um CNPJ com 14 dígitos para consultar.'}));return}setConsulting(true);setMsg('Consultando CNPJ...');try{const r=await fetch(`/api/financeiro/filiais/consulta/cnpj/${digits(form.cnpj)}`);if(!r.ok)throw new Error(await friendly(r));const d=await r.json() as Partial<Form>;setForm(f=>({...f,...Object.fromEntries(Object.entries(d).filter(([,v])=>typeof v==='string'&&v))}));setMsg('Dados consultados. Revise as informações antes de salvar.')}catch(e){setMsg(e instanceof Error?e.message:'Falha ao consultar CNPJ.')}finally{setConsulting(false)}};
 const consultCep=async()=>{if(digits(form.cep).length!==8){setErrors(e=>({...e,cep:'Informe um CEP com 8 dígitos para consultar.'}));return}setConsulting(true);setMsg('Consultando CEP...');try{const r=await fetch(`/api/financeiro/filiais/consulta/cep/${digits(form.cep)}`);if(!r.ok)throw new Error(await friendly(r));const d=await r.json() as Partial<Form>;setForm(f=>({...f,...d,numero:f.numero,complemento:f.complemento}));setMsg('Endereço localizado. Confirme número e complemento antes de salvar.')}catch(e){setMsg(e instanceof Error?e.message:'Falha ao consultar CEP.')}finally{setConsulting(false)}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!validate()){setMsg('Revise os campos destacados.');return}setBusy(true);setMsg('Salvando...');try{const r=await fetch('/api/financeiro/filiais'+(id?'/'+id:''),{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,cnpj:digits(form.cnpj),cep:digits(form.cep),uf:form.uf.toUpperCase()})});if(!r.ok)throw new Error(await friendly(r));setMsg('Filial salva com sucesso.');setId(null);setForm({...empty});await load()}catch(e){setMsg(e instanceof Error?e.message:'Não foi possível salvar a filial.')}finally{setBusy(false)}};
 const field=(k:keyof Form,label:string,required=false,extra?:React.ReactNode)=><label className="text-sm font-medium text-slate-700 dark:text-slate-200"><span>{label}{required&&<span className="ml-1 text-red-600" aria-hidden="true">*</span>}</span><div className="mt-1 flex gap-2"><input value={String(form[k])} onChange={e=>change(k,e.target.value as never)} aria-invalid={Boolean(errors[k])} aria-describedby={errors[k]?`${k}-error`:undefined} className={`w-full rounded-xl border px-3 py-2.5 outline-none transition focus:ring-2 focus:ring-red-500 dark:bg-slate-900 ${errors[k]?'border-red-500':'border-slate-300 dark:border-slate-700'}`}/>{extra}</div>{errors[k]&&<span id={`${k}-error`} role="alert" className="mt-1 block text-xs text-red-600">{errors[k]}</span>}</label>;
 return <div className="space-y-6"><header><h1 className="text-2xl font-bold">Filiais</h1><p className="text-sm text-slate-500">Cadastre e revise os CNPJs das filiais. A visão consolidada continua sendo o padrão.</p></header>
 <form onSubmit={save} noValidate className="space-y-5 rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div><h2 className="text-lg font-semibold">{title}</h2><p className="text-xs text-slate-500">Campos marcados com * são obrigatórios.</p></div><div className="grid gap-4 md:grid-cols-3">{field('codigo','Código',true)}{field('nome','Nome operacional',true)}<label className="text-sm font-medium">Tipo<select value={form.tipoEstabelecimento} onChange={e=>change('tipoEstabelecimento',e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2.5 dark:bg-slate-900"><option value="MATRIZ">Matriz</option><option value="FILIAL">Filial</option></select></label>{field('cnpj','CNPJ',false,<button type="button" disabled={consulting} onClick={consultCnpj} className="whitespace-nowrap rounded-xl border px-3 py-2 text-sm font-semibold disabled:opacity-50">Consultar</button>)}{field('razaoSocial','Razão social')}{field('nomeFantasia','Nome fantasia')}{field('inscricaoEstadual','Inscrição estadual')}{field('inscricaoMunicipal','Inscrição municipal')}{field('cep','CEP',false,<button type="button" disabled={consulting} onClick={consultCep} className="whitespace-nowrap rounded-xl border px-3 py-2 text-sm font-semibold disabled:opacity-50">Buscar CEP</button>)}{field('logradouro','Logradouro')}{field('numero','Número')}{field('complemento','Complemento')}{field('bairro','Bairro')}{field('cidade','Cidade')}{field('uf','UF')}<label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form.ativo} onChange={e=>change('ativo',e.target.checked)}/>Filial ativa</label></div><div className="flex flex-wrap items-center gap-3"><button disabled={busy||consulting} className="rounded-xl bg-red-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy?'Salvando...':id?'Atualizar filial':'Cadastrar filial'}</button>{id&&<button type="button" onClick={cancel} className="rounded-xl border px-5 py-2.5">Cancelar</button>}{msg&&<span role="status" className="text-sm text-slate-600 dark:text-slate-300">{msg}</span>}</div></form>
 <div className="overflow-auto rounded-2xl border"><table className="w-full text-sm"><thead><tr className="bg-slate-50 dark:bg-slate-900"><th className="p-3 text-left">Filial</th><th>CNPJ</th><th>Tipo</th><th>Cidade/UF</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3"><b>{x.nome}</b><div>{x.codigo}</div></td><td>{x.cnpj||'Não associado'}</td><td>{x.tipo_estabelecimento}</td><td>{[x.cidade,x.uf].filter(Boolean).join('/')||'—'}</td><td>{x.ativo?'Ativa':'Inativa'}</td><td className="p-2"><button type="button" onClick={()=>edit(x)} className="rounded-lg border px-3 py-1.5">Editar</button></td></tr>)}</tbody></table></div></div>;
}
