export const DASHBOARD_TV_CATALOG = [
  {
    tipo: 'operacional-resumo',
    grupo: 'Operacional',
    titulo: 'Visão operacional',
    formato: 'kpis',
    financeiro: false,
  },
  {
    tipo: 'operacional-alertas',
    grupo: 'Operacional',
    titulo: 'Serviços em atenção',
    formato: 'tabela',
    financeiro: false,
  },
  {
    tipo: 'os-backlog',
    grupo: 'Ordens de Serviço',
    titulo: 'Backlog de OS',
    formato: 'kpis',
    financeiro: false,
  },
  {
    tipo: 'os-distribuicao',
    grupo: 'Ordens de Serviço',
    titulo: 'OS por tipo, UF e atendente',
    formato: 'graficos',
    financeiro: false,
  },
  {
    tipo: 'propostas-resumo',
    grupo: 'Propostas',
    titulo: 'Desempenho de propostas',
    formato: 'kpis',
    financeiro: false,
  },
  {
    tipo: 'propostas-top-clientes',
    grupo: 'Propostas',
    titulo: 'Clientes com propostas aprovadas',
    formato: 'ranking',
    financeiro: false,
  },
  {
    tipo: 'grandes-projetos-resumo',
    grupo: 'Grandes Projetos',
    titulo: 'Carteira de grandes projetos',
    formato: 'kpis',
    financeiro: false,
  },
  {
    tipo: 'grandes-projetos-execucao',
    grupo: 'Grandes Projetos',
    titulo: 'Execução e margem percentual',
    formato: 'lista',
    financeiro: false,
  },
  {
    tipo: 'financeiro-inadimplencia',
    grupo: 'Financeiro',
    titulo: 'Inadimplência percentual',
    formato: 'percentual',
    financeiro: true,
  },
] as const;
